version: "3.9"

services:
  radar_fit:
    container_name: radar_fit
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      frc_test_backend:
        condition: service_healthy
    volumes:
      - .:/app

  frc_test_backend:
    container_name: frc_test_backend
    image: radarfit
    ports:
      - 5431:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s